from . import medicine_feature
from . import product_product
from . import barcode_sequence
from . import product_barcode
from . import product_template
from . import res_config_settings
from . import commission
from . import pos_session
from . import pharmacy_product